version: '3.8'

# docker-compose up -d
# docker-compose down

services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Local directory mount
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge